std_msgs/Header                 header
uint8 car_num
float64 lat # [deg] in global coords
float64 lon # [deg] in global coords
float64 hgt # [deg] in global coords
float64 vx # [m/s] in veh local coords
float64 vy # [m/s] in veh local coords
float64 vz # [m/s] in veh local coords
float64 yaw # rad from North, CCW positive
float64 pitch # rad
float64 roll # rad
float64 del_x # [m] in vehicle local coords
float64 del_y # [m] in vehicle local coords
float64 del_z # [m] in vehicle local coords