std_msgs/Header                 header
float32 map_sensor
float32 lambda_sensor
float32 fuel_level
float32 fuel_pressure # [kPa]
float32 engine_oil_pressure # [kPa]
float32 engine_oil_temperature # [deg Celcius]
float32 engine_coolant_temperature # [deg Celcius]
float32 engine_coolant_pressure # [kPa]
float32 engine_rpm # [rpm]
bool engine_on_status
bool engine_run_switch_status
float32 throttle_position # [%]
int8 current_gear
int8 gear_shift_status
float32 transmission_oil_pressure # [kPa]
float32 transmission_accumulator_pressure # [kPa]
float32 transmission_oil_temperature # [deg Celcius]
float32 vehicle_speed_kmph # [km/h]
float32 torque_wheels_nm # [Nm]