FROM ghcr.io/automotiveaichallenge/aichallenge2023-racing/autoware-universe-no-cuda:latest

RUN rm -rf /autoware/install/tier4_*_launch

ENV ROS_LOCALHOST_ONLY 1
ENV RMW_IMPLEMENTATION rmw_cyclonedds_cpp
ENV export RCUTILS_COLORIZED_OUTPUT 1
